// examples/solid-router/src/pages/_app.tsx
import { ParentProps } from 'solid-js'

import { A, useModals, useNavigate } from '@/router'

export const Catch = (props: { error: Error; reset: () => void }) => {
  return (
    <div>
      Something went wrong: {props.error.message}
      Caught at _app error boundary
      <button onClick={props.reset}>reset</button>
    </div>
  )
}

export const Pending = () => <div>Loading from _app...</div>

export default function App(props: ParentProps) {
  const navigate = useNavigate()
  const modals = useModals()

  const a = () => navigate('/about')
  const b = () => navigate('/posts/:id/:pid?', { params: { id: 'xyz' } })

  return (
    <section style={{ margin: '24px' }}>
      <header style={{ display: 'flex', gap: '24px' }}>
        <A href="/">Home</A>
        <A href="/about">About</A>
        <A href="/posts/:id" params={{ id: 'xyz' }}>
          Post by Id
        </A>
        <button onClick={() => modals.open('/modal', { at: '/posts' })}>Open global modal</button>
      </header>

      <main>{props.children}</main>
    </section>
  )
}

// examples/react-router/src/pages/_app.tsx
import { Outlet } from 'react-router'

import { Link, useModals, useNavigate, useParams } from '../router'

export const Catch = () => {
  return <div>Something went wrong... Caught at _app error boundary</div>
}

export const Pending = () => <div>Loading from _app...</div>

export default function App() {
  const navigate = useNavigate()
  const modals = useModals()
  const { id, pid } = useParams('/posts/:id/:pid?')

  const a = () => navigate('/posts/:id', { params: { id: 'a' } })
  const b = () => navigate('/posts/:id', { params: { id: '' } })
  const c = () => navigate(-1)
  const d = () => navigate('/posts/:id/deep', { params: { id: 'd' } })
  const e = () => navigate('/posts/:id/deep', { params: { id: 'e' } })

  return (
    <section style={{ margin: 24 }}>
      <header style={{ display: 'flex', gap: 24 }}>
        <Link to="/">Home</Link>
        <Link to={{ pathname: '/about' }}>About</Link>
        <Link to="/posts">Posts</Link>
        <Link to="/posts/:id/:pid?" params={{ id: '1', pid: '2' }}>
          Posts by id/pid
        </Link>
        <Link to="/posts/:id" params={{ id: 'id' }}>
          Posts by id
        </Link>
        <button onClick={() => modals.open('/modal')}>Global modal at current route</button>
        <button onClick={() => modals.open('/modal', { at: '/about' })}>Global modal at /about</button>
        <button onClick={e}>navigate to</button>
      </header>

      <main>
        <Outlet />
      </main>
    </section>
  )
}
